#!/bin/bash
# -----------------------------------------------------------------------------
# Script: setup_dev_env.sh
# Description: Interactive utility to set up a standardized development
#              environment by installing dependencies and personalizing config files.
# DevOps Value: Reduces developer onboarding time and ensures environment consistency.
# -----------------------------------------------------------------------------

# --- 1. Best Practices and Logging Setup ---

set -euo pipefail

# ��� LOG FILE ADJUSTMENT: Define the custom log directory and file path
LOG_DIR="$HOME/team4tech-groupb-automationscripts/members/brandon"
LOG_FILE="$LOG_DIR/dev_setup_$(date +%F).log"

# Create the log directory if it doesn't exist.
mkdir -p "$LOG_DIR"

# Function to log messages to both stdout and the log file
function log_message() {
    local TYPE="$1"
    local MESSAGE="$2"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] ${TYPE}: ${MESSAGE}" | tee -a "$LOG_FILE"
}

# Trap function to catch errors and provide clean exit
function cleanup_on_error() {
    log_message "FATAL" "Script failed near line $1. Review log file for details: $LOG_FILE"
    exit 1
}
trap 'cleanup_on_error $LINENO' ERR

log_message "INFO" "Starting Interactive Development Environment Setup..."

# Determine if sudo is needed and check for root permissions
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    log_message "INFO" "Script not running as root. Will attempt to use 'sudo' for package installation."
    SUDO="sudo"
fi

# --- 2. OS and Package Manager Detection (Robust Check) ---

PKG_MGR=""
# Check for Debian/Ubuntu using the 'apt' command
if command -v apt &> /dev/null; then
    PKG_MGR="apt"
# Check for RHEL/CentOS using the 'yum' or 'dnf' command
elif command -v yum &> /dev/null || command -v dnf &> /dev/null; then
    PKG_MGR="yum"
else
    log_message "ERROR" "Unsupported package manager found. Only Debian/Ubuntu (apt) and RHEL/CentOS/Fedora (yum/dnf) are supported."
    log_message "INFO" "Please ensure your system has a valid package manager installed and accessible."
    exit 1
fi
log_message "INFO" "Detected OS and set package manager to $PKG_MGR."

# --- 3. Interactive Input and Validation (Input Parameters) ---

PROJECT_NAME=""
GIT_USER=""

# Input Parameter 1: Project Name (Required)
read -r -p "Enter your project name (e.g., frontend-api): " PROJECT_NAME
if [[ -z "$PROJECT_NAME" ]]; then
    log_message "ERROR" "Project name cannot be empty."
    exit 1
fi

# Input Parameter 2: GitHub Username (Required for config)
read -r -p "Enter your GitHub username for configuration: " GIT_USER
if [[ -z "$GIT_USER" ]]; then
    log_message "ERROR" "GitHub username cannot be empty."
    exit 1
fi

log_message "INFO" "User inputs received: Project=$PROJECT_NAME, GitUser=$GIT_USER"

# --- 4. Dependency Installation (Idempotency) ---

REQUIRED_PACKAGES=("git" "curl" "jq" "nginx")
log_message "INFO" "Checking and installing required system packages."

# Run a single package list update to improve efficiency
if [ "$PKG_MGR" = "apt" ]; then
    log_message "INFO" "Updating package list..."
    $SUDO $PKG_MGR update -y
fi

for PACKAGE in "${REQUIRED_PACKAGES[@]}"; do
    if ! command -v "$PACKAGE" &> /dev/null; then
        log_message "INFO" "Installing $PACKAGE..."
        if $SUDO $PKG_MGR install -y "$PACKAGE"; then
            log_message "SUCCESS" "$PACKAGE installed."
        else
            log_message "ERROR" "Failed to install $PACKAGE."
            exit 1
        fi
    else
        log_message "INFO" "$PACKAGE is already installed. Skipping."
    fi
done

# --- 5. Configuration Templating ---

log_message "INFO" "Creating configuration template."

TEMPLATE_CONTENT=$(cat <<'EOF'
# app-config.yaml for ${PROJECT_NAME}
# This file was generated by setup_dev_env.sh
project_name: PLACEHOLDER_PROJECT_NAME
default_user: PLACEHOLDER_GIT_USER
log_level: DEBUG
ssh_key_path: ~/.ssh/id_rsa
EOF
)

CONFIG_FILE="$HOME/.$PROJECT_NAME.config.yaml"

if [[ -f "$CONFIG_FILE" ]]; then
    log_message "WARN" "Existing config file found at $CONFIG_FILE. Backing up..."
    $SUDO mv "$CONFIG_FILE" "$CONFIG_FILE.bak.$(date +%s)"
fi

# Create new config file from template content
echo "$TEMPLATE_CONTENT" > "$CONFIG_FILE"

# Use sed to substitute the placeholders with user input
sed -i "s|PLACEHOLDER_PROJECT_NAME|$PROJECT_NAME|g" "$CONFIG_FILE"
sed -i "s|PLACEHOLDER_GIT_USER|$GIT_USER|g" "$CONFIG_FILE"

log_message "SUCCESS" "Configuration file created and customized at $CONFIG_FILE."
log_message "INFO" "Setting restrictive permissions on configuration file."
chmod 600 "$CONFIG_FILE" # Security Best Practice: restrict access

# --- 6. Final Verification and User Instructions (End) ---

log_message "INFO" "Running final environment checks..."

# Check if the configuration file is readable and secure
if [[ -r "$CONFIG_FILE" ]]; then
    log_message "SUCCESS" "Configuration file is readable."
else
    log_message "FATAL" "Configuration file is not readable. Check permissions."
    exit 1
fi

echo "
==================================================
✅ SETUP COMPLETE SUCCESSFULLY!
==================================================
Your personalized development environment is ready.

- Packages (git, curl, jq, nginx) verified.
- Configuration file created and secured: ${CONFIG_FILE}

��� Next Steps for ${GIT_USER}:
    1. Clone your main project: git clone git@github.com:${GIT_USER}/${PROJECT_NAME}.git
    2. Start the application using your team's standard command.
    3. Review the complete log: ${LOG_FILE}
=================================================="

log_message "INFO" "Script execution finished."